name: social
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  http: ^0.13.4
  objectbox: ^1.4.1
  objectbox_flutter_libs: ^1.4.1
  path_provider: ^2.0.0
  infinite_scroll_pagination: ^3.1.0
  get: ^4.6.1
  sqflite: ^2.0.2
  path: ^1.8.0
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  
  

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^1.0.0
  objectbox_generator: any
  hive_generator: ^1.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.1


flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/instagram.png"
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/surface.jpg"
  android: true
  ios: true

flutter:

  uses-material-design: true 

  assets:
    - assets/images/surface.jpg
    - assets/images/instagram.png
